FROM       ssdit/bareos-base:experimental-17.1.3
MAINTAINER Ryann Micua <rmicua@ssd.org>

ENV DEBIAN_FRONTEND noninteractive

RUN bash -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" > /etc/apt/sources.list.d/postgres.list'
RUN bash -c 'wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | apt-key add -'

RUN apt-get update && apt-get install -y postgresql-client-9.6

RUN bash -c "echo 'bareos-database-common bareos-database-common/dbconfig-install boolean false' | debconf-set-selections"
RUN bash -c "echo 'bareos-database-common bareos-database-common/install-error select ignore' | debconf-set-selections"
RUN bash -c "echo 'bareos-database-common bareos-database-common/database-type select psql' | debconf-set-selections"
RUN bash -c "echo 'bareos-database-common bareos-database-common/missing-db-package-error select ignore' | debconf-set-selections"

RUN apt-get install -y bareos bareos-database-postgresql

RUN tar cfvz /etc.tgz /etc/bareos/

ADD docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod u+x /docker-entrypoint.sh

EXPOSE 9101

VOLUME /etc/bareos

ENTRYPOINT ["/docker-entrypoint.sh"]
#CMD ["/usr/sbin/bareos-dir", "-c", "/etc/bareos/bareos-dir.conf", "-u", "bareos", "-f"]
CMD ["/usr/sbin/bareos-dir", "-u", "bareos", "-f"]

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
